FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py

# Definir engine WEBJS para Waha
ENV WHATSAPP_DEFAULT_ENGINE=WEBJS

# Expõe as portas 5000 para Flask e 3000 para WAHA
EXPOSE 5000 3000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
