services:

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
